spring:
  datasource:
    #数据库配置
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 19961013
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
        log4j2:
          enabled: true
  cloud:
    sentinel:
      transport:
        port: 8077
        dashboard: 127.0.0.1:8077
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: 4c499d3d-e19b-4e3e-94a8-78efd1327ae4
            dataId: sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

